title: Danilo Monteiro's Portfolio
description: I turn coffee into code. Use tabs over spaces and never broke production.
baseurl: ""
url: "https://d0gster.github.io"
repository: d0gster/d0gster.github.io

remote_theme: yousinix/portfolYOU

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jemoji
  - jekyll-gist
  - kramdown-parser-gfm

author:
  name: Danilo Monteiro
  image: https://i.imgur.com/kq01ycK.jpeg
  email: dev.danilomonteiro@gmail.com
  github: d0gster
  linkedin: danilo-monteir0

collections:
  projects:
    output: true
    permalink: /projects/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

exclude:
  - README.md
  - LICENSE
  - vendor/
  - .bundle/